package com.qin.domain;
// Generated 2017-10-22 14:53:45 by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.springframework.beans.factory.annotation.Autowired;

import com.qin.domain.User;

/**
 * TBoard generated by hbm2java
 * NONE：不适用缓存
 * READ_ONLY：只读模式，如果对数据进行更新操作，则会产生异常
 * READ_WRITE：读写模式，该模式会更新缓存的时候会对环村里面的数据加锁，其他事物如果去取相应的缓存数据，发现被锁了，就会直接去数据库查询
 * NONSTRICT_READ_WRITE:不严格的读写模式，使用该模式不会对缓存数据加锁
 */
@Entity(name="Board")
@Table(name = "t_board")
@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)

public class Board extends BaseDomain{
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "board_id", unique = true, nullable = false)
	private Integer boardId;
	@Column(name = "board_name", nullable = false, length = 150)
	private String boardName;
	@Column(name = "board_desc")
	private String boardDesc;
	@Column(name = "topic_num", nullable = false)
	private int topicNum;
	
	@Autowired
	@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, mappedBy = "manBoards", fetch = FetchType.LAZY)
	private Set<User> users = new HashSet<User>();

	public Board() {
	}

	public Board(String boardName, int topicNum) {
		this.boardName = boardName;
		this.topicNum = topicNum;
	}

	public Board(String boardName, String boardDesc, int topicNum) {
		this.boardName = boardName;
		this.boardDesc = boardDesc;
		this.topicNum = topicNum;
	}

	
	public Integer getBoardId() {
		return this.boardId;
	}

	public void setBoardId(Integer boardId) {
		this.boardId = boardId;
	}

	
	public String getBoardName() {
		return this.boardName;
	}

	public void setBoardName(String boardName) {
		this.boardName = boardName;
	}

	
	public String getBoardDesc() {
		return this.boardDesc;
	}

	public void setBoardDesc(String boardDesc) {
		this.boardDesc = boardDesc;
	}

	
	public int getTopicNum() {
		return this.topicNum;
	}

	public void setTopicNum(int topicNum) {
		this.topicNum = topicNum;
	}

	public Set<User> getUsers() {
		return users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}
	

}
