package com.qin.domain;
// Generated 2017-10-22 14:53:45 by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * TLoginLog generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "t_login_log")
public class LoginLog implements java.io.Serializable {

	private Integer loginLogId;
	
	@Autowired
	@ManyToOne
	@JoinColumn(name = "user_id")
	private User user;
	private String ip;
	private Date loginDatetime;

	public LoginLog() {
	}

	public LoginLog(String ip, Date loginDatetime) {
		this.ip = ip;
		this.loginDatetime = loginDatetime;
	}

	public LoginLog(User user, String ip, Date loginDatetime) {
		this.user = user;
		this.ip = ip;
		this.loginDatetime = loginDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "login_log_id", unique = true, nullable = false)
	public Integer getLoginLogId() {
		return this.loginLogId;
	}

	public void setLoginLogId(Integer loginLogId) {
		this.loginLogId = loginLogId;
	}
	
	
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	

	@Column(name = "ip", nullable = false, length = 30)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "login_datetime", nullable = false, length = 30)
	public Date getLoginDatetime() {
		return this.loginDatetime;
	}

	public void setLoginDatetime(Date loginDatetime) {
		this.loginDatetime = loginDatetime;
	}

}
